version: '3'

volumes:
  dbdata:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/blog/static:/static
    depends_on:
      - web

  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    # command: python manage.py runserver 0.0.0.0:8000
    command: uwsgi --socket :8001 --module mysite.wsgi
    volumes:
      - ./src:/code
      - ./src/blog/static:/static
    ports:
      - "8001"
    depends_on:
      - db