# Generated by Django 2.0.4 on 2018-04-15 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='AdsName')),
                ('html', models.TextField(blank=True, verbose_name='AdsHtml')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Analytics')),
                ('html', models.TextField(blank=True, verbose_name='AnalyticsHtml')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='CategoryName')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UnName', max_length=255, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Comment')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='com_icon/', verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('src', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='TempFile')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(help_text='Save file after sending.', upload_to='uploads/%Y/%m/%d/', verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='LinkName')),
                ('adrs', models.CharField(max_length=255, verbose_name='Address')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
        migrations.CreateModel(
            name='PopularPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titile')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('page_view', models.IntegerField(verbose_name='PageView')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Body')),
                ('thumnail', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Thumbnail')),
                ('is_publick', models.BooleanField(default=True, verbose_name='Publicable?')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='Category')),
                ('friend_posts', models.ManyToManyField(blank=True, related_name='_post_friend_posts_+', to='blog.Post', verbose_name='RelatedArticle')),
            ],
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UnName', max_length=255, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Comment')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='com_icon/', verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='TargetComment')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ký Sự Nhật Bản', max_length=255, verbose_name='Tiltle')),
                ('header_text', models.TextField(default='Ký Sự Nhật Bản', max_length=255, verbose_name='HeaderText')),
                ('description', models.TextField(default='Description', max_length=255, verbose_name='Description')),
                ('author', models.CharField(default='Huutrinh', max_length=255, verbose_name='Author')),
                ('author_mail', models.EmailField(default='trinhsp89@gmail.com', max_length=255, verbose_name='AuthorAddress')),
                ('color', models.CharField(choices=[('primary', '青色'), ('secondary', '灰色'), ('success', '緑色'), ('info', '水色'), ('warning', '黄色'), ('danger', '赤'), ('dark', '黒')], default='primary', max_length=30, verbose_name='サイトテーマ色')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='TagName')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Post', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='TargetArticle'),
        ),
    ]
