# Generated by Django 2.2.7 on 2019-12-19 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='link',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitedetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='html',
            field=models.TextField(blank=True, verbose_name='AnalyticHtml'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Analytic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='comment_thumbnail/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='file',
            name='src',
            field=models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='TempFile'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(help_text='Save after sending.', upload_to='images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='popularpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnail/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='recomment_thumbnail/%Y/%m/%d//', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='TargetArticle'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='author_mail',
            field=models.EmailField(default='trinhsp89@gmail.com', max_length=255, verbose_name='AuthorMail'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='color',
            field=models.CharField(choices=[('primary', '青色'), ('secondary', '灰色'), ('success', '緑色'), ('info', '水色'), ('warning', '黄色'), ('danger', '赤'), ('dark', '黒')], default='primary', max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='header_text',
            field=models.TextField(default='Ký Sự Nhật Bản\n', max_length=255, verbose_name='HeaderText'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='title',
            field=models.CharField(default='Engineer Diary', max_length=255, verbose_name='Title'),
        ),
    ]
