# Generated by Django 2.2.7 on 2019-12-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191219_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='title',
            field=models.CharField(default="Huutrinh's blog", max_length=255, verbose_name='Title'),
        ),
    ]
