# Generated by Django 2.2.7 on 2019-12-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180416_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='header_text',
            field=models.TextField(default='Blog của trinhnh\n[filter url]https://github.com/naritotzawa/django-torina-blog<split>Githubのソースコード[end]', max_length=255, verbose_name='ヘッダーのテキスト'),
        ),
    ]
